server:
  port: 8080
front:
  host:
    http://localhost:5173,
    https://hackathon-git-main-eireensid.vercel.app
spring:
  datasource:
    url: jdbc:postgresql://postgresdb:5432/postgres
    username: postgres
    password: postgres
    hikari:
      connection-timeout: 30000
      minimum-idle: 5
      maximum-pool-size: 10
      max-lifetime: 30000
      idle-timeout: 60000
      auto-commit: true
  flyway:
    enabled: true
    validate-on-migrate: true
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: false