server:
  port: 8080
front:
  host:
    http://localhost:5173,
    https://hackathon-pummelerdevs-projects.vercel.app,
    https://hackathon-livid-seven.vercel.app,
    https://hackathon-git-master-pummelerdevs-projects.vercel.app
spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://postgresdb:5432/postgres?useSSL=false}
    username: postgres
    password: postgres
    hikari:
      connection-timeout: 30000
      minimum-idle: 5
      maximum-pool-size: 10
      max-lifetime: 30000
      idle-timeout: 60000
      auto-commit: true
  flyway:
    enabled: true
    validate-on-migrate: true
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: false
  servlet:
    multipart:
      enabled: on
      max-file-size: 1MB
      max-request-size: 1MB