server:
  port: 8080
front:
  host: http://localhost
spring:
  datasource:
    #    url: jdbc:postgresql://localhost:35432/postgres-back
    url: jdbc:h2:mem:h2-back
    username: postgres
    password: postgres
    hikari:
      connection-timeout: 30000
      minimum-idle: 5
      maximum-pool-size: 10
      max-lifetime: 30000
      idle-timeout: 60000
      auto-commit: true
  flyway:
    enabled: true
    validate-on-migrate: true
  jpa:
    show-sql: true
    properties:
      hibernate:
#        dialect: org.hibernate.dialect.PostgreSQLDialect
